/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.termoVista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.JToggleButton;
import my.termoModelo.ModeloTermo;

/**
 *
 * @author juan
 */
public class VistaUI extends javax.swing.JFrame {
    private ControladorTermo miControl;
    private ModeloTermo miModelo;
    /**
     * Creates new form VistaUI
     */
    public VistaUI() {
        initComponents();
        miModelo = new ModeloTermo();
        miControl = new ControladorTermo(this, miModelo);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelDias = new javax.swing.JPanel();
        jLabelLunes = new javax.swing.JLabel();
        jLabelMartes = new javax.swing.JLabel();
        jLabelMiercoles = new javax.swing.JLabel();
        jLabelJueves = new javax.swing.JLabel();
        jLabelViernes = new javax.swing.JLabel();
        jLabelSabado = new javax.swing.JLabel();
        jLabelDomingo = new javax.swing.JLabel();
        jPanelMedio = new javax.swing.JPanel();
        jPanelPantalla = new javax.swing.JPanel();
        jTextFieldHora = new javax.swing.JTextField();
        jTextFieldTemp = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanelSelectProgram = new javax.swing.JPanel();
        jLabelActualProgram = new javax.swing.JLabel();
        jComboBoxPrograms = new javax.swing.JComboBox<>();
        jPanelSelectInit = new javax.swing.JPanel();
        jLabelHoras = new javax.swing.JLabel();
        jSpinnerSelectHora = new javax.swing.JSpinner();
        jButtonIniciar = new javax.swing.JButton();
        jLabelMinima = new javax.swing.JLabel();
        jSpinnerMinima = new javax.swing.JSpinner();
        jLabelMaxima = new javax.swing.JLabel();
        jSpinnerMaxima = new javax.swing.JSpinner();
        jPanelSelectHoras = new javax.swing.JPanel();
        jToggleButtonHora03 = new javax.swing.JToggleButton();
        jToggleButtonHora47 = new javax.swing.JToggleButton();
        jToggleButtonHora811 = new javax.swing.JToggleButton();
        jToggleButtonHora1215 = new javax.swing.JToggleButton();
        jToggleButtonHora1619 = new javax.swing.JToggleButton();
        jToggleButtonHora2023 = new javax.swing.JToggleButton();
        jPanelOpciones = new javax.swing.JPanel();
        jToggleButtonOn = new javax.swing.JToggleButton();
        jToggleButtonManual = new javax.swing.JToggleButton();
        jToggleButtonAuto = new javax.swing.JToggleButton();
        jToggleButtonEdit = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jLabelLunes.setText("Lunes");
        jPanelDias.add(jLabelLunes);

        jLabelMartes.setText("Martes");
        jPanelDias.add(jLabelMartes);

        jLabelMiercoles.setText("Miércoles");
        jPanelDias.add(jLabelMiercoles);

        jLabelJueves.setText("Jueves");
        jPanelDias.add(jLabelJueves);

        jLabelViernes.setText("Viernes");
        jPanelDias.add(jLabelViernes);

        jLabelSabado.setText("Sábado");
        jPanelDias.add(jLabelSabado);

        jLabelDomingo.setText("Domingo");
        jPanelDias.add(jLabelDomingo);

        getContentPane().add(jPanelDias);

        jPanelMedio.setLayout(new java.awt.GridLayout(0, 1));

        jPanelPantalla.setLayout(new java.awt.GridLayout(1, 0));

        jTextFieldHora.setEditable(false);
        jTextFieldHora.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jTextFieldHora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldHora.setText("Hora");
        jPanelPantalla.add(jTextFieldHora);

        jTextFieldTemp.setEditable(false);
        jTextFieldTemp.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jTextFieldTemp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTemp.setText("19ºC");
        jTextFieldTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTempActionPerformed(evt);
            }
        });
        jPanelPantalla.add(jTextFieldTemp);

        jPanelMedio.add(jPanelPantalla);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jLabelActualProgram.setText("Programa actual:");

        jComboBoxPrograms.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Programa 1", "Programa 2", "Programa 3", "Programa 4" }));
        jComboBoxPrograms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProgramsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSelectProgramLayout = new javax.swing.GroupLayout(jPanelSelectProgram);
        jPanelSelectProgram.setLayout(jPanelSelectProgramLayout);
        jPanelSelectProgramLayout.setHorizontalGroup(
            jPanelSelectProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSelectProgramLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSelectProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelActualProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPrograms, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanelSelectProgramLayout.setVerticalGroup(
            jPanelSelectProgramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSelectProgramLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelActualProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxPrograms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel5.add(jPanelSelectProgram);

        jLabelHoras.setText("Horas:");

        jButtonIniciar.setText("Iniciar");
        jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });

        jLabelMinima.setText("Mínima:");

        jLabelMaxima.setText("Máxima:");

        javax.swing.GroupLayout jPanelSelectInitLayout = new javax.swing.GroupLayout(jPanelSelectInit);
        jPanelSelectInit.setLayout(jPanelSelectInitLayout);
        jPanelSelectInitLayout.setHorizontalGroup(
            jPanelSelectInitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSelectInitLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSelectInitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelSelectInitLayout.createSequentialGroup()
                        .addComponent(jLabelHoras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerSelectHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSelectInitLayout.createSequentialGroup()
                        .addComponent(jLabelMinima)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSpinnerMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSelectInitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelSelectInitLayout.createSequentialGroup()
                        .addComponent(jLabelMaxima)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSelectInitLayout.setVerticalGroup(
            jPanelSelectInitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSelectInitLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanelSelectInitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMinima, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSpinnerMinima, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMaxima, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSpinnerMaxima, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSelectInitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelSelectInitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSpinnerSelectHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonIniciar)))
                .addContainerGap())
        );

        jPanel5.add(jPanelSelectInit);

        jToggleButtonHora03.setText("0-3");
        jToggleButtonHora03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonHora03ActionPerformed(evt);
            }
        });

        jToggleButtonHora47.setText("4-7");
        jToggleButtonHora47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonHora47ActionPerformed(evt);
            }
        });

        jToggleButtonHora811.setText("8-11");
        jToggleButtonHora811.setMaximumSize(new java.awt.Dimension(48, 27));
        jToggleButtonHora811.setMinimumSize(new java.awt.Dimension(48, 27));
        jToggleButtonHora811.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonHora811ActionPerformed(evt);
            }
        });

        jToggleButtonHora1215.setText("12-15");
        jToggleButtonHora1215.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonHora1215ActionPerformed(evt);
            }
        });

        jToggleButtonHora1619.setText("16-19");
        jToggleButtonHora1619.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonHora1619ActionPerformed(evt);
            }
        });

        jToggleButtonHora2023.setText("20-23");

        javax.swing.GroupLayout jPanelSelectHorasLayout = new javax.swing.GroupLayout(jPanelSelectHoras);
        jPanelSelectHoras.setLayout(jPanelSelectHorasLayout);
        jPanelSelectHorasLayout.setHorizontalGroup(
            jPanelSelectHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSelectHorasLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanelSelectHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToggleButtonHora03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButtonHora1215, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSelectHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSelectHorasLayout.createSequentialGroup()
                        .addComponent(jToggleButtonHora1619)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonHora2023))
                    .addGroup(jPanelSelectHorasLayout.createSequentialGroup()
                        .addComponent(jToggleButtonHora47, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonHora811, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanelSelectHorasLayout.setVerticalGroup(
            jPanelSelectHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSelectHorasLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanelSelectHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonHora03)
                    .addComponent(jToggleButtonHora47)
                    .addComponent(jToggleButtonHora811, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSelectHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonHora1215)
                    .addComponent(jToggleButtonHora1619)
                    .addComponent(jToggleButtonHora2023))
                .addGap(30, 30, 30))
        );

        jPanel5.add(jPanelSelectHoras);

        jPanelMedio.add(jPanel5);

        getContentPane().add(jPanelMedio);

        jToggleButtonOn.setText("Encender");
        jToggleButtonOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonOnActionPerformed(evt);
            }
        });
        jPanelOpciones.add(jToggleButtonOn);

        buttonGroup1.add(jToggleButtonManual);
        jToggleButtonManual.setText("Manual");
        jToggleButtonManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonManualActionPerformed(evt);
            }
        });
        jPanelOpciones.add(jToggleButtonManual);

        buttonGroup1.add(jToggleButtonAuto);
        jToggleButtonAuto.setText("Automático");
        jToggleButtonAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAutoActionPerformed(evt);
            }
        });
        jPanelOpciones.add(jToggleButtonAuto);

        buttonGroup1.add(jToggleButtonEdit);
        jToggleButtonEdit.setText("Editar");
        jPanelOpciones.add(jToggleButtonEdit);

        getContentPane().add(jPanelOpciones);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonHora47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonHora47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonHora47ActionPerformed

    private void jToggleButtonHora1215ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonHora1215ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonHora1215ActionPerformed

    private void jToggleButtonHora1619ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonHora1619ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonHora1619ActionPerformed

    private void jComboBoxProgramsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProgramsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxProgramsActionPerformed

    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonIniciarActionPerformed

    private void jToggleButtonManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonManualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonManualActionPerformed

    private void jToggleButtonAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonAutoActionPerformed

    private void jTextFieldTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTempActionPerformed

    private void jToggleButtonHora03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonHora03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonHora03ActionPerformed

    private void jToggleButtonOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonOnActionPerformed
        miControl.powerButtonSwitch();
    }//GEN-LAST:event_jToggleButtonOnActionPerformed

    private void jToggleButtonHora811ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonHora811ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonHora811ActionPerformed
    
    
    /**
     * Obtiene el jPanelDias
     * @return jPanelDias
     */
    public JPanel getPanelDias(){
        return this.jPanelDias;
    }
    
    
    /**
     * Obtiene el jPanelOpciones
     * @return jPanelOpciones
     */
    public JPanel getPanelOpciones(){
        return this.jPanelOpciones;
    }

    
    /**
     * Obtiene el jPanelMedio
     * @return jPanelOpciones
     */
    public JPanel getPanelMedio(){
        return this.jPanelMedio;
    }
    
    
    /**
     * Obtiene el jToggleButtonAuto
     * @return jToggleButtonAuto
     */
    public JToggleButton getToggleButtonAuto(){
        return this.jToggleButtonAuto;
    }
    
    
    /**
     * Obtiene el jToggleButtonOn
     * @return jToggleButtonOn
     */
    public JToggleButton getToggleButtonOn(){
        return this.jToggleButtonOn;
    }
    
    
    /**
     * Obtiene el jToggleButtonOn
     * @return jToggleButtonOn
     */
    public JToggleButton getToggleButtonManual(){
        return this.jToggleButtonManual;
    }
    
    
    /**
     * Obtiene el jToggleButtonEdit
     * @return jToggleButtonEdit
     */
    public JToggleButton getToggleButtonEdit(){
        return this.jToggleButtonEdit;
    }
    
    /**
     * Obtiene el jLabelMinima
     * @return jLabelMinima
     */
    public JLabel getLabelMinima(){
        return this.jLabelMinima;
    }
    
    /**
     * Obtiene el jLabelMaxima
     * @return jLabelMaxima
     */
    public JLabel getLabelMaxima(){
        return this.jLabelMaxima;
    }
    
    /**
     * Obtiene el jSpinnerMaxima
     * @return jSpinnerMaxima
     */
    public JSpinner getSpinnerMaxima(){
        return this.jSpinnerMaxima;
    }
    
    /**
     * Obtiene el jSpinnerMinima
     * @return jSpinnerMinima
     */
    public JSpinner getSpinnerMinima(){
        return this.jSpinnerMinima;
    }
    
    /**
     * Obtiene el jSpinnerSelectHora
     * @return jSpinnerSelectHora
     */
    public JSpinner getSpinnerSelectHora(){
        return this.jSpinnerSelectHora;
    }
    
    /**
     * Obtiene el jButtonIniciar
     * @return jButtonIniciar
     */
    public JButton getButtonIniciar(){
        return this.jButtonIniciar;
    }
    
    /**
     * Obtiene el jLabelHoras
     * @return jLabelHoras
     */
    public JLabel getLabelHoras(){
        return this.jLabelHoras;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JComboBox<String> jComboBoxPrograms;
    private javax.swing.JLabel jLabelActualProgram;
    private javax.swing.JLabel jLabelDomingo;
    private javax.swing.JLabel jLabelHoras;
    private javax.swing.JLabel jLabelJueves;
    private javax.swing.JLabel jLabelLunes;
    private javax.swing.JLabel jLabelMartes;
    private javax.swing.JLabel jLabelMaxima;
    private javax.swing.JLabel jLabelMiercoles;
    private javax.swing.JLabel jLabelMinima;
    private javax.swing.JLabel jLabelSabado;
    private javax.swing.JLabel jLabelViernes;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelDias;
    private javax.swing.JPanel jPanelMedio;
    private javax.swing.JPanel jPanelOpciones;
    private javax.swing.JPanel jPanelPantalla;
    private javax.swing.JPanel jPanelSelectHoras;
    private javax.swing.JPanel jPanelSelectInit;
    private javax.swing.JPanel jPanelSelectProgram;
    private javax.swing.JSpinner jSpinnerMaxima;
    private javax.swing.JSpinner jSpinnerMinima;
    private javax.swing.JSpinner jSpinnerSelectHora;
    private javax.swing.JTextField jTextFieldHora;
    private javax.swing.JTextField jTextFieldTemp;
    private javax.swing.JToggleButton jToggleButtonAuto;
    private javax.swing.JToggleButton jToggleButtonEdit;
    private javax.swing.JToggleButton jToggleButtonHora03;
    private javax.swing.JToggleButton jToggleButtonHora1215;
    private javax.swing.JToggleButton jToggleButtonHora1619;
    private javax.swing.JToggleButton jToggleButtonHora2023;
    private javax.swing.JToggleButton jToggleButtonHora47;
    private javax.swing.JToggleButton jToggleButtonHora811;
    private javax.swing.JToggleButton jToggleButtonManual;
    private javax.swing.JToggleButton jToggleButtonOn;
    // End of variables declaration//GEN-END:variables
}
